kind: Kueue
apiVersion: kueue.openshift.io/v1
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kueue-operator
  name: cluster
spec:
  config:
    integrations:
      frameworks:
        - BatchJob
    preemption:
      # Classical (default), FairSharing
      preemptionPolicy: Classical
    workloadManagement:
      # QueueName (default), None
      labelPolicy: QueueName
  # logLevel: Debug
  # operatorLogLevel: Debug
  managementState: Managed
