apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "Leader Worker Set Operator"
  labels:
    openshift.io/cluster-monitoring: 'true'
  name: openshift-lws-operator
