apiVersion: batch/v1
kind: Job
metadata:
  generateName: example-gpu-
  labels:
    kueue.x-k8s.io/queue-name: user-queue
  # name: example
spec:
  template:
    spec:
      containers:
        - name: cuda-sample-vector-add
          image: "nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda11.7.1-ubuntu20.04"
          resources:
            limits:
              nvidia.com/gpu: 1
      restartPolicy: Never
  backoffLimit: 4
