---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kueue-batch-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kueue-batch-user-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: kueue-users
